global.selpage = []
global.page = []
global.load = []
global.search = []
global.search_keyword = []
global.course = []
global.courseKeyword = []
global.mode = []
global.nowpage = []

//미사용
global.name = []
global.id = []
global.nickname = []
global.profile_image = []
global.email = []
global.birthday = []
global.login = []
global.realname = []
global.mobile = []
global.mobile_e164 = []
global.gender = []
global.birthyear = []