# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Expo GitHub Action
      # You may pin to the exact commit or the version.
      # uses: expo/expo-github-action@f98a64c8874c4a163514273f34306f403e962350
      uses: expo/expo-github-action@7.2.0
      with:
        # Expo CLI version to install
        expo-version: 6.0.2
        # If Expo CLI should be cached to speed up installation
        expo-cache: true
        # EAS CLI version to install
        eas-version: 0.54.1
        # If EAS CLI should be cached to speed up installation
        eas-cache: true
        # The package manager used to install the CLIs
        packager: yarn
        # If the action should patch the ENOSPC errors
        patch-watchers: true
        # Your Expo token, for authentication. (use with secrets)
        token: xnvgTP56iRZXWWvGmzyv4aYaGQF5ELL380uUnzjL
        # A custom remote cache key to use for EAS CLI.
        eas-cache-key: dlstn0722!
        # A custom remote cache key to use for Expo CLI.
        expo-cache-key: dlstn0722! 
        # Your Expo username, for authentication.
        username: ruddls030
        # Your Expo password, for authentication. (use with secrets)
        password: Dlstn0722!
